#!/data/data/com.termux/files/usr/bin/bash

clear
../new-miner/cpuminer-2 \
	-a yescrypt \
	-o stratum+tcp://singapore.mining-dutch.nl:9992 \
	-u maribun20.worker2 \
	-p "d=0.1" \
	-t 4 \
	--cpu-priority 0 \
	--cpu-affinity 0xf -x SOCKS5://127.0.0.1:2080
